"
A simple widget to display a list of classes


```
WidgetClassListPresenter new open
```
"
Class {
	#name : 'AnObsoleteWidgetClassListPresenter',
	#superclass : 'SpPresenter',
	#instVars : [
		'list'
	],
	#category : 'CodeOfSpec20Book-Chapter08',
	#package : 'CodeOfSpec20Book',
	#tag : 'Chapter08'
}

{ #category : 'examples' }
AnObsoleteWidgetClassListPresenter class >> example [

	self new open
]
