"
A specialized code browser reusing different presenters

```
ProtocolCodeBrowserPresenter new open
```
"
Class {
	#name : 'AnObsoleteProtocolCodeBrowserPresenter',
	#superclass : 'SpPresenter',
	#instVars : [
		'text',
		'viewer'
	],
	#category : 'CodeOfSpec20Book-Chapter08',
	#package : 'CodeOfSpec20Book',
	#tag : 'Chapter08'
}

{ #category : 'examples' }
AnObsoleteProtocolCodeBrowserPresenter class >> example [

	self new open
]
